const fs = require('fs');

let code = fs.readFileSync('src/pages/Dashboard.tsx', 'utf8');

const oldStats = `  const stats = [
    {
      id: 1,
      icon: "💰",
      title: "Total Earned",
      value: formatShortNumber(realStats.totalEarned),
      rawValue: realStats.totalEarned,
      sub: "Coins",
      color: "text-indigo-600",
      bg: "to-indigo-50",
      arrBg: "bg-indigo-500",
    },
    {
      id: 2,
      icon: "📋",
      title: "Total Tasks",
      value: realStats.totalTasks.toLocaleString(),
      rawValue: realStats.totalTasks,
      sub: "Tasks",
      color: "text-blue-600",
      bg: "to-blue-50",
      arrBg: "bg-blue-500",
    },
    {
      id: 3,
      icon: "👥",
      title: "Total Referrals",
      value: realStats.totalReferrals.toLocaleString(),
      rawValue: realStats.totalReferrals,
      sub: "Users",
      color: "text-emerald-500",
      bg: "to-emerald-50",
      arrBg: "bg-emerald-500",
    },
    {
      id: 4,
      icon: "📺",
      title: "Ads Watched",
      value: (user?.dailyAdsWatched || 0).toLocaleString(),
      rawValue: user?.dailyAdsWatched || 0,
      sub: "Ads",
      color: "text-red-500",
      bg: "to-red-50",
      arrBg: "bg-red-500",
    },
    {
      id: 5,
      icon: "🎁",
      title: "Total Rewards",
      value: formatShortNumber(user?.vaBalance || 0),
      rawValue: user?.vaBalance || 0,
      sub: "Coins",
      color: "text-amber-500",
      bg: "to-amber-50",
      arrBg: "bg-amber-500",
    },
    {
      id: 6,
      icon: "🔥",
      title: "Daily Streak",
      value: realStats.dailyStreak.toLocaleString(),
      rawValue: realStats.dailyStreak,
      sub: "Days",
      color: "text-orange-500",
      bg: "to-orange-50",
      arrBg: "bg-orange-500",
    },
    {
      id: 7,
      icon: "⏳",
      title: "Pending Tasks",
      value: realStats.activeTasks.toLocaleString(),
      rawValue: realStats.activeTasks,
      sub: "Tasks",
      color: "text-blue-600",
      bg: "to-blue-50",
      arrBg: "bg-blue-500",
    },
    {
      id: 8,
      icon: "✅",
      title: "Completed",
      value: ((user as any)?.tasksCompleted || 0).toLocaleString(),
      rawValue: (user as any)?.tasksCompleted || 0,
      sub: "Tasks",
      color: "text-green-500",
      bg: "to-green-50",
      arrBg: "bg-green-500",
    },
    {
      id: 9,
      icon: "🏆",
      title: "Global Rank",
      value: \`#\${(user as any)?.globalRank || "—"}\`,
      sub: "Leaderboard",
      color: "text-purple-600",
      bg: "to-purple-50",
      arrBg: "bg-purple-500",
    },
    {
      id: 10,
      icon: "🎯",
      title: "Active Tasks",
      value: ((user as any)?.activeTasks || 0).toLocaleString(),
      rawValue: (user as any)?.activeTasks || 0,
      sub: "Tasks",
      color: "text-cyan-500",
      bg: "to-cyan-50",
      arrBg: "bg-cyan-500",
    },
    {
      id: 11,
      icon: "🎮",
      title: "Games Played",
      value: ((user as any)?.gamesPlayed || 0).toLocaleString(),
      rawValue: (user as any)?.gamesPlayed || 0,
      sub: "Games",
      color: "text-violet-500",
      bg: "to-violet-50",
      arrBg: "bg-violet-500",
    },
    {
      id: 12,
      icon: "⭐",
      title: "User Level",
      value: (user?.currentLevel || 1).toLocaleString(),
      rawValue: user?.currentLevel || 1,
      sub: "Level",
      color: "text-yellow-600",
      bg: "to-yellow-50",
      arrBg: "bg-yellow-500",
    },
  ];`;

const newStats = `  const stats = [
    {
      id: 2,
      icon: "📋",
      title: "Total Tasks",
      value: realStats.totalTasks.toLocaleString(),
      rawValue: realStats.totalTasks,
      sub: "Tasks",
      color: "text-blue-600",
      bg: "to-blue-50",
      arrBg: "bg-blue-500",
    },
    {
      id: 3,
      icon: "👥",
      title: "Total Referrals",
      value: realStats.totalReferrals.toLocaleString(),
      rawValue: realStats.totalReferrals,
      sub: "Users",
      color: "text-emerald-500",
      bg: "to-emerald-50",
      arrBg: "bg-emerald-500",
    },
    {
      id: 4,
      icon: "📺",
      title: "Ads Watched",
      value: (user?.dailyAdsWatched || 0).toLocaleString(),
      rawValue: user?.dailyAdsWatched || 0,
      sub: "Ads",
      color: "text-red-500",
      bg: "to-red-50",
      arrBg: "bg-red-500",
    },
    {
      id: 5,
      icon: "🎁",
      title: "Total Rewards",
      value: formatShortNumber(user?.vaBalance || 0),
      rawValue: user?.vaBalance || 0,
      sub: "Coins",
      color: "text-amber-500",
      bg: "to-amber-50",
      arrBg: "bg-amber-500",
    },
    {
      id: 6,
      icon: "🔥",
      title: "Daily Streak",
      value: realStats.dailyStreak.toLocaleString(),
      rawValue: realStats.dailyStreak,
      sub: "Days",
      color: "text-orange-500",
      bg: "to-orange-50",
      arrBg: "bg-orange-500",
    },
    {
      id: 9,
      icon: "🏆",
      title: "Global Rank",
      value: \`#\${realStats.globalRank || "—"}\`,
      sub: "Leaderboard",
      color: "text-purple-600",
      bg: "to-purple-50",
      arrBg: "bg-purple-500",
    }
  ];`;

code = code.replace(oldStats, newStats);

fs.writeFileSync('src/pages/Dashboard.tsx', code);
